; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v2 on Mon Feb 04 2019 20:28:59 GMT+0000 (Western European Standard Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


