; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v2 on Mon Feb 04 2019 20:28:59 GMT+0000 (Western European Standard Time)

