; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2 on Mon Feb 04 2019 20:28:59 GMT+0000 (Western European Standard Time)
; Wait for set temperatures to be reached
M116 P0

